apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "pulse-backend-deployment"
  namespace: "default"
  labels:
    app: "pulse-backend-deployment"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "pulse-backend-deployment"
  template:
    metadata:
      labels:
        app: "pulse-backend-deployment"
    spec:
      containers:
        - name: "pulse-backend-image-sha256-1"
          image: gcr.io/PROJECT_ID/IMAGE:TAG
          ports:
            - containerPort: 8080
