apiVersion: apps/v1
kind: Deployment
metadata:
  name: pulse-events-backend

spec:
  replicas: 1
  selector:
    matchLabels:
      app: pulse-events-backend
  template:
    metadata:
      labels:
        app: pulse-events-backend
    spec:
      containers:
        - name: app
          image: gcr.io/PROJECT_ID/IMAGE:TAG
          imagePullPolicy: Always
