apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "pulse-backend-deployment"
  namespace: "default"
  labels:
    app: "pulse-backend-deployment"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "pulse-backend-deployment"
  template:
    metadata:
      labels:
        app: "pulse-backend-deployment"
    spec:
      containers:
        - name: "pulse-backend-image"
          image: gcr.io/PROJECT_ID/IMAGE:TAG
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATA_MONGODB_URI
              value: "${SPRING_DATA_MONGODB_URI}"
            - name: SPRING_DATA_MONGODB_DATABASE
              value: "${SPRING_DATA_MONGODB_DATABASE}"
            - name: JWT_SECRET_KEY
              value: "${JWT_SECRET_KEY}"
            - name: JWT_EXPIRATION
              value: "${JWT_EXPIRATION}"
