import "./globals.css";
import { Inter } from "next/font/google";
import { Suspense } from "react";
import { Metadata } from "next";
import NavBar from "@/Components/nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Pulse Events",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="bg-gray-50 h-full">
      <body
        className={`${inter.className} flex h-full w-full justify-start items-start flex-col`}
      >
        <NavBar />
        <div className="w-full h-full mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
          {children}
        </div>
      </body>
    </html>
  );
}
