apiVersion: "autoscaling/v2"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "pulse-backend-deployment-hpa-8cxf"
  namespace: "default"
  labels:
    app: "pulse-backend-deployment"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "pulse-backend-deployment"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: "Resource"
      resource:
        name: "cpu"
        target:
          type: "Utilization"
          averageUtilization: 80
