apiVersion: v1
kind: Service
metadata:
  name: pulse-backend-service
  namespace: default
  type: LoadBalancer
  labels:
    app: pulse-backend
spec:
  ports:
    - port: 80 # Port exposed by the service
      targetPort: 8080 # Port on the pods
  selector:
    app: pulse-backend
